# Generated by Django 5.0.3 on 2024-05-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoapp', '0004_rename_interests_guestprofile_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topics', models.ManyToManyField(related_name='hashtags', to='echoapp.topic')),
            ],
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='hashtags',
            field=models.ManyToManyField(related_name='guest_profiles', to='echoapp.hashtag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hashtags',
            field=models.ManyToManyField(related_name='user_profiles', to='echoapp.hashtag'),
        ),
    ]
